### ISSUE TITLE
postinst issues

### ISSUE THREAD

**Issue by chompy-enbala** [jiro4989/build-deb-action#20]
Team,

I'm having issues getting the packages built by this action to understand the `postinst` file:
`D000002: vmaintscript_installed nonexistent postinst`

I've tried dropping `postinst` into the root folder of the packaging and it doesn't see it.

Any ideas on how `postinst` needs to be set here to adjust permissions of files after the installation?

**Comment by jiro4989** [comment]
@chompy-enbala  I added a new sample workflow now.

https://github.com/jiro4989/build-deb-action/blob/master/.github/workflows/test.yml#L93-L130

```bash
          mkdir -p .debpkg/DEBIAN
          cat << E > .debpkg/DEBIAN/postinst
          #!/bin/bash
          set -eu
          echo postinst $@
          E
          chmod +x .debpkg/DEBIAN/postinst
```

[GitHub Actions log](https://github.com/jiro4989/build-deb-action/runs/1393387354?check_suite_focus=true#step:5:9)

Please try creating a `<package_root>/DEBIAN/postinst` script.

**Comment by chompy-enbala** [comment]
This worked!!! Thank you so much @jiro4989  <3
