### ISSUE TITLE
Consider uploading to https://hub.docker.com/ and pulling the image instead of building the docker image in the action

### ISSUE THREAD

**Issue by AskAlice** [jiro4989/build-deb-action#23]
could improve the speed it takes to run the action

**Comment by jiro4989** [comment]
@AskAlice  Thanks.
That is so fast.

![image](https://user-images.githubusercontent.com/13825004/120849215-b9f9bd80-c5b0-11eb-8e0b-fb9e7bc11043.png)

**Comment by AskAlice** [comment]
might also want to do this with the RPM action.

Thanks <3
