### ISSUE TITLE
dpkg-deb fails without declaration of description

### ISSUE THREAD

**Issue by usimd** [jiro4989/build-deb-action#25]
When running the action without declaring a `desc` property, `dpkg-deb` fails with:

> dpkg-deb: error: parsing file '.debpkg/DEBIAN/control' near line 5 package 'package:arm64':
 end of file before value of field 'Description' (missing final newline)

According to the README, this should be working. All other parameters were defined.

**Comment by jiro4989** [comment]
@usimd
