### ISSUE TITLE
Additional files within the DEBIAN folder?

### ISSUE THREAD

**Issue by domwhewell** [jiro4989/build-deb-action#35]
Hi,
Is it possible to configure aditional files inside of the DEBIAN folder such as postinst files or others?
https://www.debian.org/doc/manuals/maint-guide/dother.en.html

**Comment by jiro4989** [comment]
@domwhewell  Yes.
Please try this.

https://github.com/jiro4989/build-deb-action/issues/20#issuecomment-726415368

And I wrote a postinst script sample to [README](https://github.com/jiro4989/build-deb-action/commit/51a3897a36a862e85f49758459a21a59206528eb).
