### ISSUE TITLE
2 warnings from deprecated commands 

### ISSUE THREAD

**Issue by userdocs** [jiro4989/build-deb-action#36]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jiro4989** [comment]
I fixed it.

https://github.com/jiro4989/build-deb-action/releases/tag/v2.5.2

**Comment by userdocs** [comment]
@jiro4989 thanks. All the warnings are gone and no other issues.
