### ISSUE TITLE
Base ubuntu image 20.04 → 22.04 causes failures extracting on Debian

### ISSUE THREAD

**Issue by userdocs** [jiro4989/build-deb-action#40]
I tested 2.6.0 and a downgrade back to 2.5.2

```
dpkg-deb: error: archive 'debian-stretch-zlib-ng-amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive debian-stretch-zlib-ng-amd64.deb (--install):
```

Fails (2.6.0) - https://github.com/userdocs/openssl-crossbuild/actions/runs/3305620199/jobs/5455875489

Works (2.5.2) - https://github.com/userdocs/openssl-crossbuild/actions/runs/3307014775/jobs/5458331009

So I think the problems is Ubuntu added zst compression but Debian has not (some google results)

https://unix.stackexchange.com/a/669008

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664

**Comment by jiro4989** [comment]
I'm so sorry.
I temporarily reverted 2.6.0 changed.
Please use v2.6.1.

**Comment by userdocs** [comment]
It's not your fault directly. If you check the issue Debian seemed annoyed Ubuntu forced this change on them and they have to add zst support. 

Maybe you can do this and manually set compression type?

https://manpages.ubuntu.com/manpages/jammy/man1/dpkg-deb.1.html

```
 -Zcompress-type
           Specify which compression type to use when building a package.  Allowed values are
           gzip, xz (since dpkg 1.15.6), zstd (since dpkg 1.19.0.5ubuntu2) and none (default is
           zstd).
```

**Comment by jiro4989** [comment]
@userdocs I added a manual parameter.
https://github.com/jiro4989/build-deb-action/releases/tag/v2.7.0

**Comment by userdocs** [comment]
Ok thanks, i'll test it out and get back you to

**Comment by userdocs** [comment]
I have updated to 2.70 and added the compression option and it seems to be working fine.

https://github.com/userdocs/openssl-crossbuild/actions/runs/3314109672

None of the Debian matrix builds have failed. I think it's safe to close for now as this is solid solution to address the problem since the image is updated to 22.04 and works.

Thanks.
