### ISSUE TITLE
Multiline string does not work

### ISSUE THREAD

**Issue by vanillajonathan** [jiro4989/build-deb-action#43]
Such as having a a description that spans multiple lines.

> dpkg-deb: error: parsing file '.debpkg/DEBIAN/control' near line 2 

Example:
```yaml
desc: >
    This is the leading paragraph.

    This is another paragraph.
```

It works fine with `build-rpm-action` though. The string replacement is different.

`build-deb-action` uses:
```nim
.replace("{DESC}", desc)
```
`build-rpm-action` uses:
```nim
.replace("{{DESC}}", desc)
```
with two curly braces.

So for `build-deb-action` the result becomes:

    --description:"Hello world"

for `build-rpm-action` it becomes

    '--description:Hello world'

**Comment by jiro4989** [comment]
@vanillajonathan Thanks.

This is a problem with the Description format in the debian control file.

Ref: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-description

> Those starting with a single space are part of a paragraph. Successive lines of this form will be word-wrapped when displayed. The leading space will usually be stripped off. The line must contain at least one non-whitespace character.

> Those starting with two or more spaces. These will be displayed verbatim. If the display cannot be panned horizontally, the displaying program will line wrap them “hard” (i.e., without taking account of word breaks). If it can they will be allowed to trail off to the right. None, one or two initial spaces may be deleted, but the number of spaces deleted from each line will be the same (so that you can have indenting work correctly, for example). The line must contain at least one non-whitespace character.

> Those containing a single space followed by a single full stop character. These are rendered as blank lines. This is the only way to get a blank line. [9](https://www.debian.org/doc/debian-policy/ch-controlfields.html#id24)

> Those containing a space, a full stop and some more characters. These are for future expansion. Do not use them.

---

Currently `build-deb-action` cannot handle multi-line descriptions.

This input:

```yaml
desc: >
    This is the leading paragraph.

    This is another paragraph.
```

Correctly, `build-deb-action` should generate Description in the following format:

```yaml
Description: This is the leading paragraph.
 .
 This is another paragraph.
```

Currently it outputs this:

```yaml
Description: This is the leading paragraph.

This is another paragraph.
```

So this is a bug of `build-deb-action`.
I started fixing bugs. (https://github.com/jiro4989/build-deb-action/pull/44)

**Comment by jiro4989** [comment]
@vanillajonathan I fixed this bug.

Please use `jiro4989/build-deb-action@v2` or `jiro4989/build-deb-action@v2.8.0`.

**Comment by vanillajonathan** [comment]
I seem to have a similar problem with multi-line comments in the `build-rpm-action`.

**Comment by jiro4989** [comment]
thank you. We will check that as well.

**Comment by jiro4989** [comment]
`%description` section is already available in `build-rpm-action`.
https://github.com/jiro4989/build-rpm-action/blob/d803488448e25fcf2d89376d86adab0c6b443448/template.spec#L15

This section can contain a multi-line description.
See also: [RPM Packaging Guide](https://rpm-packaging-guide.github.io/)

So the multiline `desc` problem should not occur.

**Comment by vanillajonathan** [comment]
Could you update `build-rpm-action/.github/workflows/test.yml` to feature a multi-line description?

**Comment by jiro4989** [comment]
Create issues to build-rpm-action

**Comment by jiro4989** [comment]
Conversations about bugs should be in the repository where the bug exists.

**Comment by jiro4989** [comment]
I can create an issue on build-rpm-action by myself, and I can fix bugs. But I don't want to do.

Because I want to properly record in the repository that you found the bug. You are a great contributor. I want to record your contribution in the issues.

**Comment by vanillajonathan** [comment]
Alright. I opened an issue at jiro4989/build-rpm-action/issues/9.
